version: '3.9'

services:
  lunabot:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./heart:/luna/heart
    networks:
      - luna-network

networks:
  luna-network:
    external: true